name: API Test Automation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Run API Tests
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: npm test

    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: jest-junit-report
        path: junit.xml

